[theme]
base = "dark"  # ali "light"
primaryColor = "#4CAF50"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[general]
title = "Google Drive ZIP"
favicon = "ğŸ“"
